version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:80"
    volumes:
      - .:/usr/local/apache2/htdocs
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=demo
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
